### ISSUE TITLE
Whisper example - Non-English Audio

### ISSUE THREAD

**Issue by yiqinfu** [modal-labs/modal-examples#166]
Hi! I tried the transcriber (https://modal-labs--whisper-pod-transcriber-fastapi-app.modal.run/) on non-English content, and it didn't work. Perhaps you could state on the site that only English content is supported or change the Whisper model to the one that allows for any language?

Also, a small typo on the Stable Diffusion page (https://modal.com/docs/guide/ex/stable_diffusion_cli) "Stable Ddiffusion"

**Comment by erikbern** [comment]
Thanks – that's great feedback! We'll make those changes

**Comment by astropingo** [comment]
I second the feedback. Since it is using the models `model.en`, its output is a somewhat coherent but garbage english text that has no correlation with the original text.

Maybe, for the public transcriber (modal-labs), there could be an option to choose the model without the .en version. The models work great for a variety of languages.

**Comment by thundergolfer** [comment]
@yiqinfu for the moment I've added a warning on non-English podcast search results (see PR ref'd above). Will close this issue 👍 

Thanks again for taking the time to make the issue.
