### ISSUE TITLE
Whisper example - Missing last few sentences.

### ISSUE THREAD

**Issue by cgreening** [modal-labs/modal-examples#214]
Just trying out this on a podcast I listen to and the transcription seems to be always missing the last couple of sentences.

e.g.

https://modal-labs--whisper-pod-transcriber-fastapi-app.modal.run/#/episode/4861529/d3aa80319a5ee09634115b2d97472a9b

**Comment by thundergolfer** [comment]
Thanks for the report @cgreening, there's a similar problem in one I just checked: https://modal-labs--whisper-pod-transcriber-fastapi-app.modal.run/#/episode/603405/395973d69318e935d059f39abed4ce87. 

Looks like an off-by-one error somewhere. Will look into it.

**Comment by cosimo** [comment]
@thundergolfer @cgreening 

I looked a bit into this, and one potential source of problems could be this section of `pod_transcriber/app/main.py:split_silences()`:

    # silencedetect can place the silence end *after* the end of the full audio segment.
    # Such segments definitions are negative length and invalid.
    if duration > cur_start and (duration - cur_start) > min_segment_length:
        yield cur_start, duration
        num_segments += 1

Link: https://github.com/modal-labs/modal-examples/blob/main/06_gpu_and_ml/openai_whisper/pod_transcriber/app/main.py#L276C5-L280

The second part of the condition (`and (duration - cur_start) > min_segment_length:`) could lead to missing out on a last section of the podcast file if the last silence break falls past 30s before the end of the podcast file (f.ex. 14m31s if the podcast file is 15m00s).

The last podcast segment would then be from 14:31->15:00, and thus 29s long, shorter than `min_segment_length` (default: 30s). As such, this last segment would not be considered (no `yield` call).

I could write a patch, but I don't know if this behaviour was intentional, and I haven't tried the code on my modal account. I'm afraid it would spawn "100 to 300 containers" 😅
