### ISSUE TITLE
How do I set stop_token_id in vllm_inference.py?

### ISSUE THREAD

**Issue by mochacat2001** [modal-labs/modal-examples#842]
I would like to create a dataset using Magpie, a method for creating synthetic datasets, but I don't know how to set stop_token_id. Could you please provide me with the source code of how to do this?

**Comment by charlesfrye** [comment]
Hello there!

We reserve the Issues section on this GitHub repo for problems with the examples themselves, rather than for support with using the examples. For that, you can ask in [our community Slack](https://modal.com/Slack). 

But FYI, you can set stop token IDs in vLLM with [sampling params](https://github.com/vllm-project/vllm/blob/main/vllm/sampling_params.py).
